<?php
$routes['default_controller'] = 'home';
$routes['san-pham'] = 'product/index';
$routes['san-pham/chi-tiet/(:num)'] = 'product/detail/$1'; // Chỉ chấp nhận số
$routes['trang-chu'] = 'home';
$routes['tin-tuc/.+-(\d+).html'] = 'news/category/$1';
$routes['contact'] = 'home/contact';
$routes['about'] = 'home/about';
$routes['account'] = 'user/account';
$routes['auth/google-redirect'] = 'auth/googleAuth';
$routes['auth/facebook-redirect'] = 'auth/facebookAuth';
$routes['cars-management'] = 'admin/cars';
$routes['car-assets/(:num)'] = 'admin/cars/assets/$1';
$routes['dashboard'] = 'admin/dashboard';
$routes['blogs-management'] = 'admin/posts';
$routes['help'] = 'home/help';
$routes['help/send-question'] = 'help/sendQuestion';
$routes['product/sendMail'] = 'product/sendMail';
$routes['admin/appointments'] = 'admin/appointments/index';
$routes['admin/appointments/add'] = 'admin/appointments/add';
$routes['admin/appointments/confirm/(:num)'] = 'admin/appointments/confirm/$1';
$routes['admin/appointments/cancel/(:num)'] = 'admin/appointments/cancel/$1';