<?php
$routes['default_controller'] = 'home';
$routes['san-pham'] = 'product/index';
$routes['san-pham/chi-tiet/(:num)'] = 'product/detail/$1'; // Chỉ chấp nhận số
$routes['trang-chu'] = 'home';
$routes['tin-tuc/.+-(\d+).html'] = 'news/category/$1';
$routes['contact'] = 'home/contact';
$routes['about'] = 'home/about';
$routes['account'] = 'user/account';
$routes['auth/google-redirect'] = 'auth/googleAuth';
$routes['auth/facebook-redirect'] = 'auth/facebookAuth';
$routes['cars-management'] = 'admin/cars';
$routes['car-assets/(:num)'] = 'admin/cars/assets/$1';
$routes['dashboard'] = 'admin/dashboard';
$routes['blogs-management'] = 'admin/posts';
$routes['help'] = 'home/help';
$routes['help/send-question'] = 'help/sendQuestion';
$routes['admin/faq'] = 'admin/faq/index';
$routes['admin/faq/add'] = 'admin/faq/add';
$routes['admin/faq/edit/(:num)'] = 'admin/faq/edit/$1';
$routes['admin/faq/delete/(:num)'] = 'admin/faq/delete/$1';
$routes['admin/help-question'] = 'admin/helpQuestion/index';
$routes['admin/help-question/edit/(:any)'] = 'admin/helpQuestion/edit/$1';